# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3134fab0139b0ff42542e4e9d957311c81a05dc815aa7f8f0eae2f1e31a8d9c9dc79fcc5b63baf0b865c29e9060a6bdf022ccaf7ff3163cc1f478482a4f2e2c5

test:
  secret_key_base: c27563f8a5fce58912bc1d19ff9c67695c52e39164c5e2c9445ae89be0b1742b1a2d932b5c20cd0d77676f11736fb587b40a6fa0be91dd97be7b46874fcbb1db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
